# Generated by Django 3.2.6 on 2021-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20210905_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
